/****** Object:  StoredProcedure [dbo].[SP_CONSULTAR_EQUIPO]    Script Date: 31/10/2021 22:20:54 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CONSULTAR_EQUIPO]
AS
BEGIN
	SELECT *
	FROM EQUIPOS
END